# Generated by Django 3.1.7 on 2021-03-10 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='MyNeighborsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isChef', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=2)),
                ('zipCode', models.CharField(max_length=5)),
                ('profile_imgage_url', models.ImageField(blank=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ready_eat', models.DateTimeField()),
                ('foodImgUrl', models.ImageField(blank=True, upload_to='')),
                ('delivery', models.BooleanField()),
                ('pick_up', models.BooleanField()),
                ('dine_in', models.BooleanField()),
                ('price', models.FloatField()),
                ('status', models.BooleanField()),
                ('how_many_left', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', related_query_name='menu', to='my_neighbors_api.category')),
                ('ingredients', models.ManyToManyField(related_name='menus', related_query_name='menu', to='my_neighbors_api.Ingredient')),
                ('my_neighbor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', related_query_name='menu', to='my_neighbors_api.myneighborsuser')),
            ],
        ),
    ]
