# Generated by Django 3.1.7 on 2021-03-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_neighbors_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myneighborsuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
