# Generated by Django 3.1.7 on 2021-03-14 23:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_neighbors_api', '0002_myneighborsuser_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_date', models.DateTimeField()),
                ('how_many', models.IntegerField()),
                ('delivery_date', models.TimeField()),
                ('isConfirmed', models.BooleanField()),
                ('total_cost', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('order_type', models.CharField(max_length=15)),
                ('isDelivered_user', models.BooleanField()),
                ('isDelivered_chef', models.BooleanField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('report_note', models.CharField(max_length=1000)),
                ('menu_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', related_query_name='order', to='my_neighbors_api.menu')),
                ('user_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', related_query_name='order', to='my_neighbors_api.myneighborsuser')),
            ],
        ),
        migrations.CreateModel(
            name='MenuRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_neighbors_api.menu')),
                ('my_neighbors_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_neighbors_api.myneighborsuser')),
            ],
            options={
                'verbose_name': 'rating',
                'verbose_name_plural': 'ratings',
            },
        ),
    ]
