# Generated by Django 3.1.7 on 2021-03-15 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_neighbors_api', '0004_chefrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefrating',
            name='my_user_chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chefRatings_chef', related_query_name='chefRating_chef', to='my_neighbors_api.myneighborsuser'),
        ),
        migrations.AlterField(
            model_name='chefrating',
            name='my_user_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chefRatings_user', related_query_name='chefRating_user', to='my_neighbors_api.myneighborsuser'),
        ),
    ]
