# Generated by Django 3.1.7 on 2021-03-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_neighbors_api', '0005_auto_20210315_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='report_note',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
