# Generated by Django 3.1.7 on 2021-03-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_neighbors_api', '0007_auto_20210315_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='isConfirmed',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='isDelivered_chef',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='isDelivered_user',
            field=models.BooleanField(blank=True),
        ),
    ]
