# Generated by Django 3.1.7 on 2021-03-24 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_neighbors_api', '0012_menu_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chef_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_orders', related_query_name='chef_order', to='my_neighbors_api.myneighborsuser'),
        ),
    ]
