# Generated by Django 3.1.7 on 2021-03-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_neighbors_api', '0013_order_chef_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
